# Generated by Django 5.0.3 on 2024-03-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostingTable',
            new_name='JobPosting',
        ),
    ]
